---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::pyyaml=6.0.2
  - conda-forge::python=3.11.11
  - pip:
      - metaspace2020==2.0.9
