---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "dorothea_differential"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.3.1
  - bioconda::r-tidyverse=2.0.0
  - conda-forge::r-tibble=3.2.1
  - conda-forge::r-ggrepel=0.9.5
  - bioconda::bioconductor-decoupler=2.8.0
