name: dorothea_differential_limma

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bioconductor-decoupler=2.8.0
  - bioconda::r-tidyverse=2.0.0
  - conda-forge::r-base=4.3.1
  - conda-forge::r-ggrepel=0.9.5
  - conda-forge::r-tibble=3.2.1
